# -*- coding: utf-8 -*-
"""Project1_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXT9LNesrl1k5Bbi-aBvDemtUW1WmQkh
"""

import pandas as pd

df = pd.read_csv("vgsales.csv")
df.head()

df.info()

print('There are', df['Year'].isnull().sum(), 'null values present in the year column')

total_rows = print("Total number of rows in the data is",df.shape[0])
percentage_null = print("The Percentage of Null Values in year column is", round((271/16598)*100),"%")

round(df['Year'].median())

round(df['Year'].mean())

df['Year'].mode()

df['Year'] = df['Year'].fillna(df['Year'].median())

df_before_2005 = df[df['Year'] < 2005]  # Data before 2005
df_2005_and_after = df[df['Year'] >= 2005]  # Data from 2005 and later

df_before_2005.head()

df_2005_and_after.head()

mean_pre = round(df_before_2005['Global_Sales'].mean(),2)

mean_post = round(df_2005_and_after['Global_Sales'].mean(),2)

print(f"The mean of the Global Sales before 2005: {mean_pre}")
print(f"The mean of the Global Sales on and after 2005: {mean_post}")

if mean_pre > mean_post:
    print('The Global Sales average is higher before 2005')
else:
    print('The Global Sales average is higher after 2005')

a = []
for i in df['Year']:
    if i < 2005:
       a.append('Pre-2005')
    else:
       a.append('Post-2005')
df['year_label'] = a

df.head()